disabled_rules:
  - multiple_closures_with_trailing_closure
  - force_cast

trailing_whitespace:
  ignores_empty_lines: true

vertical_whitespace:
  max_empty_lines: 3

identifier_name:
  allowed_symbols: ['_']
  excluded: ['id']
  
line_length:
  ignores_comments: true
